export const desserts = [
  {
    id: 1,
    url: '1.jpg',
    category: 'Waffle',
    title: 'Waffle with Berries',
    price: '$6.50',
  },
  {
    id: 2,
    url: '2.jpg',
    category: 'Crème Brûlée',
    title: 'Vanilla Bean Crème Brûlée',
    price: '$7.00',
  },
  {
    id: 3,
    url: '3.jpg',
    category: 'Macaron',
    title: 'Macaron Mix of Five',
    price: '$8.00',
  },
  {
    id: 4,
    url: '4.jpg',
    category: 'Tiramisu',
    title: 'Classic Tiramisu',
    price: '$5.50',
  },
  {
    id: 5,
    url: '5.jpg',
    category: 'Baklava',
    title: 'Pistachio Baklava',
    price: '$4.00',
  },
  {
    id: 6,
    url: '6.jpg',
    category: 'Pie',
    title: 'Lemon Meringue Pie',
    price: '$5.00',
  },
  {
    id: 7,
    url: '7.jpg',
    category: 'Cake',
    title: 'Red Velvet Cake',
    price: '$4.50',
  },
  {
    id: 8,
    url: '8.jpg',
    category: 'Brownie',
    title: 'Salted Caramel Brownie',
    price: '$5.50',
  },
  {
    id: 9,
    url: '9.jpg',
    category: 'Panna Cotta',
    title: 'Vanilla Panna Cotta',
    price: '$6.50',
  },
];
